export const FLOWERS = [
  {
    id: 1,
    name: "Red Roses Bunch",
    hindi: "लाल गुलाब",
    price: 499,
    originalPrice: 699,
    rating: 4.8,
    reviews: 128,
    image: "https://images.unsplash.com/photo-1548094990-c16ca90f1f0d?w=400&h=500&fit=crop",
    badge: "Bestseller",
    badgeColor: "rose",
    category: "Roses",
    available: true,
    description: "Fresh red roses, perfect for gifting and wedding décor.",
    minQty: "50 stems",
  },
  {
    id: 2,
    name: "Marigold Garland",
    hindi: "गेंदे की माला",
    price: 299,
    originalPrice: 399,
    rating: 4.9,
    reviews: 245,
    image: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=400&h=500&fit=crop",
    badge: "Farm Fresh",
    badgeColor: "farm",
    category: "Marigold",
    available: true,
    description: "Traditional marigold garlands for every auspicious occasion.",
    minQty: "10 kg",
  },
  {
    id: 3,
    name: "Jasmine Bunch",
    hindi: "चमेली का गुच्छ",
    price: 199,
    originalPrice: 249,
    rating: 4.7,
    reviews: 89,
    image: "https://images.unsplash.com/photo-1490750967868-88df5691cc09?w=400&h=500&fit=crop",
    badge: "Fragrant",
    badgeColor: "leaf",
    category: "Jasmine",
    available: true,
    description: "Pure white jasmine with intoxicating fragrance, ideal for puja.",
    minQty: "200 stems",
  },
  {
    id: 4,
    name: "Pink Lilies",
    hindi: "गुलाबी लिली",
    price: 599,
    originalPrice: 799,
    rating: 4.6,
    reviews: 64,
    image: "https://images.unsplash.com/photo-1558603668-6570496b66f8?w=400&h=500&fit=crop",
    badge: "Pre-Book",
    badgeColor: "amber",
    category: "Lilies",
    available: false,
    description: "Elegant pink lilies for wedding and event decoration.",
    minQty: "50 stems",
  },
  {
    id: 5,
    name: "Mixed Bouquet",
    hindi: "मिक्स गुलदस्ता",
    price: 799,
    originalPrice: 999,
    rating: 4.9,
    reviews: 312,
    image: "https://images.unsplash.com/photo-1487530811015-780dfc6b0d26?w=400&h=500&fit=crop",
    badge: "Popular",
    badgeColor: "rose",
    category: "Bouquets",
    available: true,
    description: "A beautiful mix of seasonal flowers, perfect for gifting.",
    minQty: "10 bouquets",
  },
  {
    id: 6,
    name: "Purple Orchids",
    hindi: "बैंगनी ऑर्किड",
    price: 899,
    originalPrice: 1199,
    rating: 4.8,
    reviews: 47,
    image: "https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=400&h=500&fit=crop",
    badge: "Premium",
    badgeColor: "purple",
    category: "Orchids",
    available: true,
    description: "Exotic purple orchids, premium choice for corporate events.",
    minQty: "30 stems",
  },
];

export const CATEGORIES = [
  { name: "Roses",    hindi: "गुलाब",     emoji: "🌹", desc: "Elegant & Classic",       img: "https://images.unsplash.com/photo-1548094990-c16ca90f1f0d?w=300&h=300&fit=crop" },
  { name: "Marigold", hindi: "गेंदा",     emoji: "💐", desc: "Traditional & Auspicious", img: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=300&h=300&fit=crop" },
  { name: "Jasmine",  hindi: "चमेली",     emoji: "🌸", desc: "Fragrant & Pure",          img: "https://images.unsplash.com/photo-1490750967868-88df5691cc09?w=300&h=300&fit=crop" },
  { name: "Lilies",   hindi: "लिली",      emoji: "🌺", desc: "Graceful & Charming",      img: "https://images.unsplash.com/photo-1558603668-6570496b66f8?w=300&h=300&fit=crop" },
  { name: "Bouquets", hindi: "गुलदस्ता",  emoji: "💐", desc: "Perfect for Gifting",      img: "https://images.unsplash.com/photo-1487530811015-780dfc6b0d26?w=300&h=300&fit=crop" },
  { name: "Orchids",  hindi: "ऑर्किड",   emoji: "🌸", desc: "Exotic & Premium",         img: "https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=300&h=300&fit=crop" },
];

export const TESTIMONIALS = [
  {
    name: "Priya Sharma",
    location: "Delhi",
    avatar: "PS",
    rating: 5,
    text: "The flowers are so fresh and beautiful. The fragrance is just amazing! Got marigolds for my daughter's wedding — everyone loved them.",
    occasion: "Wedding",
  },
  {
    name: "Rohul Verma",
    location: "Jaipur",
    avatar: "RV",
    rating: 5,
    text: "Best quality flowers and on-time delivery. Highly recommended! We order weekly for our flower shop and the freshness is unmatched.",
    occasion: "Retail Shop",
  },
  {
    name: "Anjali Mehta",
    location: "Mumbai",
    avatar: "AM",
    rating: 5,
    text: "I ordered for my wedding and everything was perfect. Thank you PhoolMandi! The roses were fresh for 5 full days.",
    occasion: "Wedding",
  },
];

export const BULK_OCCASIONS = [
  { label: "Weddings",   hindi: "शादी",     icon: "💍", desc: "Shaadi décor, baraat, mandap" },
  { label: "Events",     hindi: "इवेंट",    icon: "🎪", desc: "Corporate, birthday, anniversary" },
  { label: "Temples",    hindi: "मंदिर",    icon: "🕌", desc: "Daily puja, festivals, offerings" },
  { label: "Corporate",  hindi: "ऑफिस",     icon: "🏢", desc: "Office décor, gifting, launches" },
];

export const TRUST_FEATURES = [
  { icon: "🌱", title: "Farm Fresh",      desc: "Handpicked Daily"         },
  { icon: "🌿", title: "Natural & Safe",  desc: "No Harmful Chemicals"     },
  { icon: "🚚", title: "Fast Delivery",   desc: "On Time, Every Time"      },
  { icon: "⭐", title: "100% Quality",    desc: "Premium Flowers"          },
];
export const NAV_LINKS = [
  { label: "Home",           href: "/" },
  { label: "About Us",       href: "about" },
  { label: "Flowers",        href: "flower" },
  { label: "Shop",           href: "shop" },
  { label: "Bulk Orders",    href: "bulk" },
  { label: "Blog",           href: "blog" },
  { label: "Contact",        href: "contact" },
];
